[sources.hgnc]
name = "HGNC"
role = "gene_identity_and_mapping"
snapshot_type = "monthly_archive"
release_date = "2026-09-04"
filename = "hgnc_complete_set_2026-09-04.tsv"
archive_page = "https://hgnc.genenames.org/download/archive/monthly/tsv/"
local_path = "data/raw/hgnc/2026-09-04/hgnc_complete_set_2026-09-04.tsv"
sha256 = "6F43D6FF43AA9FDFA5FB2F20A20A7CACE66E6E02E2A0DCF19D9B726E2E248D20"


[sources.string]
name = "STRING"
role = "gene_gene_physical_association"
version = "12.5"
taxon_id = 9606
network_type = "physical"

links_filename = "9606.protein.physical.links.detailed.v12.5.txt.gz"
aliases_filename = "9606.protein.aliases.v12.5.txt.gz"

links_local_path = "data/raw/string/v12.5/9606.protein.physical.links.detailed.v12.5.txt.gz"
aliases_local_path = "data/raw/string/v12.5/9606.protein.aliases.v12.5.txt.gz"

links_sha256 = "1AFECE499D2508D46148F647A245B5FD4E9DE89B63B64665331C8BDF8622224A"
aliases_sha256 = "B65F730B993ED0C1BD72EDF4565D3D425DB42861101B29699704810E8F125680"

[sources.ctd]
name = "CTD"
role = "chemical_gene_interaction"

snapshot_type = "rolling_report"
report_created = "2026-09-29"
download_date = "2026-10-02"

filename = "CTD_chem_gene_ixns.csv.gz"
local_path = "data/raw/ctd/2026-10-02/CTD_chem_gene_ixns.csv.gz"

sha256 = "84ed0fc7104fb886296157ea2da1690e9519ad8c8ba5450988936302c43fc82a"

source_url = "https://ctdbase.org/downloads/"



[sources.reactome]
name = "Reactome"
role = "gene_pathway"

version = "97"
release_date = "2026-06-30"
taxon_id = 9606

primary_mapping = "NCBI2Reactome"
crosscheck_mapping = "Ensembl2Reactome"

ncbi_mapping_filename = "NCBI2Reactome.txt"
ensembl_mapping_filename = "Ensembl2Reactome.txt"
pathways_filename = "ReactomePathways.txt"
disease_pathways_filename = "HumanDiseasePathways.txt"

ncbi_mapping_local_path = "data/raw/reactome/v97/NCBI2Reactome.txt"
ensembl_mapping_local_path = "data/raw/reactome/v97/Ensembl2Reactome.txt"
pathways_local_path = "data/raw/reactome/v97/ReactomePathways.txt"
disease_pathways_local_path = "data/raw/reactome/v97/HumanDiseasePathways.txt"

ncbi_mapping_sha256 = "44aec2f3d6c0d6f03268fbdc66f95a14673e86da31682b7edbd71c6c6a1ecc8d"
ensembl_mapping_sha256 = "34852dc2ac258a851bad914708c0045a636161dbbeca604f04343174cca8d7fb"
pathways_sha256 = "f6d7a2bf89b5bcfe0250a0bc7f51bff94641447911712b8ff129f5b55e52df3a"
disease_pathways_sha256 = "c044494679237839b0b0e8c132e785bf88021d92f3708d352313c928a72b32e0"

download_page = "https://reactome.org/download/current/"
release_archive = "https://doi.org/10.5281/zenodo.21383214"